### PR TITLE
Update azure to use latest, fix warnings

### PR DESCRIPTION
**Pull request by yeastplume**
Further update to CI settings and fix for warnings:

* Use `ubuntu-latest`, `windows-latest` and  `macos-latest` images
* Fix `dyn` warning
* Modify all instances of `mem::uninitialized()` to `mem::MaybeUninit::uninit().assume_init()`

### CODE REVIEW

**Comment by quentinlesceller** [comment]
Since `rustup` is installed you need to add:

macOS and Linux:
```
rustup toolchain install $RUSTUP_TOOLCHAIN
rustup default $RUSTUP_TOOLCHAIN
```

and windows:
```
rustup toolchain install %RUSTUP_TOOLCHAIN%
rustup default %RUSTUP_TOOLCHAIN%
```

**Comment by quentinlesceller** [comment]
It looks like Rustup is not included in Windows Server 2019. You might want to try the above. Otherwise you need to add:
```
    - script: |
         curl -sSf -o rustup-init.exe https://win.rustup.rs
         rustup-init.exe -y --default-toolchain %RUSTUP_TOOLCHAIN%
       displayName: Install Rust
```

**Comment by yeastplume** [comment]
Unfortunately on windows that brings us right back to the original issue:

https://dev.azure.com/mimblewimble/rust-secp256k1-zkp/_build/results?buildId=1653&view=logs&j=57b2b475-8d2a-5b04-5d48-0e52fa3a6ad3&t=5ecf445a-2f64-5417-8d77-bb5b450b5bee

**Comment by quentinlesceller** [comment]
@yeastplume can you try this on Windows:
```
rustup-init.exe toolchain install  %RUSTUP_TOOLCHAIN%
rustup-init.exe default %RUSTUP_TOOLCHAIN%
```

and remove this line:
```
rustup-init.exe -y --default-toolchain %RUSTUP_TOOLCHAIN%
```

**Comment by quentinlesceller** [comment]
Wondering if this is necessary to export again the Cargo path on Windows (`echo "##vso[task.setvariable variable=PATH;]%PATH%;%USERPROFILE%\.cargo\bin"`). Not sure which one Windows is using. Or simply try to display the toolchain before cargo to be sure.

**Comment by quentinlesceller** [comment]
Found the reason https://github.com/rust-lang/rustup/issues/2203

**Pull request merged**
