### PR TITLE
improve explanation of NUMS derivation of H and J

### PR DESCRIPTION
**Pull request by johnzweng**
## Improve documentation on how the generator points have been dervied

This PR only changes comments in the `constants.rs` file.

When I tried to understand if and how the generation points for Pedersen and Switch Commitments have been derived in a secure, nothing-up-my-sleeve (NUMS) way, I realized it would be helpful to have a better explanation in the comments.

As important properties of the commitment schemes only hold if these points are chosen transparently, I thought this should be better documented.

Let me know what you think about it, or if I should change something. 🙂

### CODE REVIEW

**Comment by antiochp** [comment]
@tromp @ignopeverell @yeastplume Any idea what's going on with this reversed byte order in J?
Did we mess something up with endianness? Or is this expected?

**Comment by tromp** [comment]
> @tromp @ignopeverell @yeastplume Any idea what's going on with this reversed byte order in J?

I didn't review this code. Forwarding to Jasper, who should know more...

**Comment by jaspervdm** [comment]
@antiochp @tromp This is the internal representation of a public key in `secp256k1_pubkey`. See also discussion in https://github.com/mimblewimble/rust-secp256k1-zkp/pull/38. We checked that these bytes in fact do represent the correct point, by comparing the compressed point with the ony originally introduced in https://github.com/mimblewimble/rust-secp256k1-zkp/pull/9/files#diff-13288cc06e4963042a0eeb6b457647dfR85. This is also explicitly tested in https://github.com/mimblewimble/secp256k1-zkp/blob/master/src/modules/commitment/tests_impl.h#L276

**Comment by jaspervdm** [comment]
@johnzweng Thank you for verifying and checking these points. The expanded documentation on the derivation is also very helpful! 👍

**Comment by johnzweng** [comment]
@jaspervdm My pleasure. Glad I could help. :-)

**Comment by johnzweng** [comment]
And the PR got the number 42.. 😄 🎉

**Comment by ignopeverell** [comment]
Merged the improvement as it was good in itself. Don't let that stop the discussion though.

**Pull request merged**
