### PR TITLE
Fuzz tests for various components

### PR DESCRIPTION
**Pull request by unseddd**
Basic fuzz drivers for `aggsig`, `ecdh` and `sign`.

### CODE REVIEW

**Comment by unseddd** [comment]
Working on `pitchfork` constant-time tests for the underlying `libsecp256k1`, but having an issue with `haybale` parsing bitcode clang generates... Not sure how to fix this, may raise an issue with `haybale` / `pitchfork` authors.

**Comment by unseddd** [comment]
@quentinlesceller are there any blockers I should address for this PR?

**Comment by quentinlesceller** [comment]
Hi @unseddd, sorry for the late response and thank you very much for this PR! I'm taking a look now.

**Comment by unseddd** [comment]
No problem, thanks for the merge :)

**Pull request merged**
